export const GATE_TEXT = {
  title: "Gate Monitor",
  description: "Simulasi pemindaian pintu gerbang K3 pintar secara real-time.",
  cameraFeed: "Live Camera Feed - Gate 1",
  activateCam: "Aktifkan Kamera",
  deactivateCam: "Nonaktifkan Kamera",
  camOff: "Kamera Fisik Off (Mode Simulasi Gambar Statis)",
  camOffDesc: "Aktifkan kamera lokal atau klik \"Simulasikan Scan\" di sebelah kanan.",
  controlTitle: "Kontrol Simulasi Demo",
  controlDesc: "Gunakan panel ini untuk mensimulasikan berbagai skenario pekerja dan K3.",
  selectWorker: "Pilih Pekerja",
  selectZone: "Zona Tujuan",
  selectScenario: "Skenario APD",
  scenarioComplete: "Lengkap (Akses Diberikan)",
  scenarioIncomplete: "Tidak Lengkap (Akses Ditolak)",
  simulateScan: "Simulasikan Scan",
  resultTitle: "Hasil Deteksi Scan",
  awaitingScan: "Menunggu Scan...",
  awaitingScanDesc: "Klik tombol Simulasikan Scan untuk memulai.",
  processing: "Memproses...",
  processingDesc: "Mencocokkan wajah dan mendeteksi kelengkapan APD.",
  complete: "LENGKAP",
  incomplete: "TIDAK LENGKAP",
  accessGranted: "Akses Gerbang Diberikan.",
  accessDenied: "Akses Gerbang Ditolak & Pelanggaran Dicatat.",
  gateStatus: "Status Gerbang",
  gateOpen: "Terbuka (GATE OPEN)",
  gateLocked: "Terkunci (GATE LOCKED)",
  ppeRequirements: "Persyaratan APD",
  waiting: "Menunggu",
  detecting: "Mendeteksi",
  notFound: "Tidak Ada",
  completeLabel: "Lengkap",
  eventLogTitle: "Live Event Log Gerbang",
  eventLogDesc: "Daftar log aktivitas keluar masuk gerbang real-time.",
  totalLogs: "Total Log",
  noActivity: "Belum ada aktivitas pemindaian.",
  analyzing: "Menganalisis Kepatuhan APD...",
} as const;
