export const ZONE_TEXT = {
  title: "Manajemen Zona Kerja",
  description: "Kelola area kerja dan atur konfigurasi APD wajib per masing-masing zona.",
  addZone: "Tambah Zona",
  complianceLabel: "Compliance Score",
  gateLabel: "Jumlah Gerbang",
  ppeLabel: "Persyaratan APD Wajib",
  noPpe: "Tidak ada APD wajib dikonfigurasi",
  manageZone: "Kelola Zona",
  newTitle: "Tambah Zona Baru",
  newDescription: "Buat area kerja baru dengan standar kepatuhan K3 sendiri.",
  formTitle: "Formulir Tambah Zona",
  formDescription: "Isi data dasar zona dan tentukan APD yang wajib dikenakan di area ini.",
  nameLabel: "Nama Zona",
  namePlaceholder: "Contoh: Zona E - Ruang Boiler",
  descLabel: "Deskripsi Zona",
  descPlaceholder: "Jelaskan aktivitas utama dan tingkat bahaya di zona ini...",
  riskLabel: "Tingkat Risiko K3",
  riskPlaceholder: "Pilih Tingkat Risiko",
  ppeChecklist: "Checklist APD Wajib",
  cancel: "Batal",
  save: "Simpan Zona",
  detailTitle: "Detail Zona",
  unknown: "Unknown Zone",
  notFound: "Zona tidak ditemukan.",
  back: "Kembali",
  gateFormat: "Gate",
};
